/**
 * Yangon township list for the address gate.
 *
 * The `townships` table exists in prod but is anon-readable and empty (0 rows,
 * verified 2026-07-06). Until it's populated, this client-side list provides
 * the picker options. Covers Yangon City (33) + Greater Yangon townships.
 */
export const YANGON_TOWNSHIPS: string[] = [
  'Ahlone',
  'Bahan',
  'Botataung',
  'Dagon',
  'Dagon Myothit (East)',
  'Dagon Myothit (North)',
  'Dagon Myothit (South)',
  'Dagon Myothit (West)',
  'Dagon Seikkan',
  'Dala',
  'Dawbon',
  'Hlaing',
  'Hlaingthaya',
  'Hlegu',
  'Hmawbi',
  'Insein',
  'Kamayut',
  'Kawthmu',
  'Kyauktan',
  'Kyeemyindaing',
  'Lanmadaw',
  'Latha',
  'Mayangone',
  'Mingalardon',
  'Mingalartaungnyunt',
  'North Okkalapa',
  'South Okkalapa',
  'Pazundaung',
  'Sanchaung',
  'Seikgyikanaungto',
  'Seikkan',
  'Shwepyithar',
  'South Dagon',
  'Tarmwe',
  'Taikkyi',
  'Thaketa',
  'Thanlyin',
  'Thingangyun',
  'Twantay',
  'Yankin',
];
